creat the files
nss-evening-cohort-05/music-history-Sanyyouisf pull request #2
Opened 2017-04-11 22:42 UTC by Sanyyouisf

2017-04-13 03:59 UTC, Sanyyouisf commented
@drdreed
I have some question for my  here:
1- i don't know why the function on line 7 in getjson.js file doesn't work.
2- the delete button in the second part( the second json file) doesn't fire , instead of  it is the same as the delete button in the  first part .
3- whey i should add this line 
$(document).ready(function(){ 
before every jquery function to make it work , it suppose to add it only one time at the beginning of the js file . 
thanks .

2017-04-15 15:08 UTC, Sanyyouisf commented
@drdreed
ready to merge now

2017-04-15 16:04 UTC, Sanyyouisf commented
@drdreed
waiting for approval to merge

2017-04-17 13:56 UTC, drdreed commented on getjson.js
> +    //to let the function work use this line
Please remove unused code.

2017-04-17 13:56 UTC, DevDreed requested changes
Please remove unused/commented out code.

2017-04-17 21:59 UTC, DevDreed approved these changes
👍

2017-04-17 21:59 UTC, Sanyyouisf commented
@drdreed
thanks

2017-04-17 22:00 UTC, merged